name: kemo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.3.0
  webview_flutter: ^4.4.4
  logger: ^1.0.0

  # Firebase dependencies
  firebase_core: ^2.17.0 # Обновленная версия Firebase Core
  firebase_storage: ^11.3.4 # Обновленная версия Firebase Storage
  cloud_firestore: ^4.7.1 # Обновленная версия Firestore
  firebase_auth: ^4.0.0
  flutter_image_compress: ^2.1.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
